<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="DESKTOP-454JC8E" name="pytest" skipped="0" tests="2" time="0.021" timestamp="2019-12-18T10:49:35.674299"><testcase classname="Tests.test_body.Test_test_body" file="Tests\test_body.py" line="15" name="test_angle" time="0.000"></testcase><testcase classname="Tests.test_body.Test_test_body" file="Tests\test_body.py" line="7" name="test_simple" time="0.001"><failure message="AssertionError: &lt;Vector.Vector object at 0x000001D94308AA08&gt; != &lt;Vector.Vector object at 0x000001D94308A948&gt;">self = &lt;test_body.Test_test_body testMethod=test_simple&gt;

    def test_simple(self):
        body = Body.simple()
    
&gt;       self.assertEqual(Vector(0, 0), body.coordinates)
E       AssertionError: &lt;Vector.Vector object at 0x000001D94308AA08&gt; != &lt;Vector.Vector object at 0x000001D94308A948&gt;

Tests\test_body.py:11: AssertionError</failure></testcase></testsuite></testsuites>