<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="DESKTOP-454JC8E" name="pytest" skipped="0" tests="5" time="0.062" timestamp="2019-12-17T22:23:00.415852"><testcase classname="Tests.test_graphics.Test_test_graphics" file="Tests\test_graphics.py" line="33" name="test_draw_buttons" time="0.002"></testcase><testcase classname="Tests.test_graphics.Test_test_graphics" file="Tests\test_graphics.py" line="40" name="test_draw_debug_units" time="0.002"><failure message="AssertionError: False is not true">self = &lt;test_graphics.Test_test_graphics testMethod=test_draw_debug_units&gt;

    def test_draw_debug_units(self):
        button = MagicMock()
    
        self.graphics.draw_buttons([button, button])
    
&gt;       self.assertTrue(self.pygame.aaline.called)
E       AssertionError: False is not true

Tests\test_graphics.py:46: AssertionError</failure></testcase><testcase classname="Tests.test_graphics.Test_test_graphics" file="Tests\test_graphics.py" line="21" name="test_draw_stats_player" time="0.003"></testcase><testcase classname="Tests.test_graphics.Test_test_graphics" file="Tests\test_graphics.py" line="27" name="test_draw_unit" time="0.003"></testcase><testcase classname="Tests.test_graphics.Test_test_graphics" file="Tests\test_graphics.py" line="15" name="test_init" time="0.002"></testcase></testsuite></testsuites>